export const ICONS1_FRAME_SIZE = 32;
export const ICONS1_COLS      = 12;

export const ICONS1: Record<string, number> = {
  // ── Fila 0 ─ Enemigos / Criaturas ────────────────────────────────────────
  monster_bear:       0,
  monster_rabbit:     1,
  // ── Fila 0 ─ Equipamiento ────────────────────────────────────────────────
  armor_chest:        2,
  weapon_sword:       3,
  shield_blue:        4,
  // ── Fila 0 ─ Recursos / Gemas ────────────────────────────────────────────
  coin_gold:          5,
  gem_pink:           6,
  magic_swirl_blue:   7,
  crystal_teal:       8,
  potion_blue:        9,
  plant_flower:       10,
  plant_leaves:       11,

  // ── Fila 1 ───────────────────────────────────────────────────────────────
  monster_boar:       12,
  monster_small:      13,
  armor_chest_brown:  14,
  weapon_sword_brown: 15,
  shield_round:       16,
  coin_silver:        17,
  gem_red:            18,
  magic_circle_blue:  19,
  crystal_orange:     20,
  potion_green:       21,
  plant_blue_flower:  22,
  gem_blue_crystal:   23,

  // ── Fila 2 ───────────────────────────────────────────────────────────────
  monster_skeleton:   24,
  monster_critter:    25,
  armor_chest_blue:   26,
  weapon_dagger:      27,
  shield_purple:      28,
  gem_red_oval:       29,
  gem_diamond_blue:   30,
  magic_swirl_gold:   31,
  crystal_teal_2:     32,
  potion_purple:      33,
  food_apple:         34,
  gem_blue_2:         35,

  // ── Fila 3 ───────────────────────────────────────────────────────────────
  helmet_dark:        36,
  monster_beast:      37,
  weapon_bow:         38,
  weapon_arrow:       39,
  shield_small:       40,
  item_star:          41,
  gem_blue_3:         42,
  magic_swirl_2:      43,
  crystal_teal_3:     44,
  potion_red:         45,
  food_mushroom:      46,
  gem_purple:         47,

  // ── Fila 4 ───────────────────────────────────────────────────────────────
  helmet_cap:         48,
  monster_boss:       49,
  weapon_staff:       50,
  weapon_knife:       51,
  item_book:          52,
  gem_green:          53,
  magic_blue_4:       54,
  crystal_teal_4:     55,
  item_scroll:        56,
  potion_orange:      57,
  food_mushroom_2:    58,
  item_arrow_blue:    59,

  // ── Fila 5 ───────────────────────────────────────────────────────────────
  helmet_skull:       60,
  monster_undead:     61,
  weapon_crossbow:    62,
  tool_wrench:        63,
  item_target:        64,
  icon_arrow_down:    65,
  gem_teal:           66,
  crystal_blue_5:     67,
  item_scroll_2:      68,
  potion_blue_2:      69,
  food_meat:          70,
  gem_purple_2:       71,

  // ── Fila 6 ───────────────────────────────────────────────────────────────
  helmet_eye:         72,
  monster_demon:      73,
  weapon_bow_2:       74,
  tool_scissors:      75,
  coin_orb:           76,
  icon_heart:         77,
  gem_diamond_red:    78,
  magic_swirl_3:      79,
  crystal_teal_5:     80,
  potion_pink:        81,
  food_fruit:         82,
  gem_teal_2:         83,

  // ── Fila 7 ───────────────────────────────────────────────────────────────
  helmet_mask:        84,
  monster_boss_2:     85,
  weapon_scythe:      86,
  shield_round_2:     87,
  icon_skull:         88,
  gem_diamond_blue_2: 89,
  magic_swirl_4:      90,
  crystal_teal_6:     91,
  item_scroll_3:      92,
  potion_yellow:      93,
  food_cooked:        94,
  gem_blue_3b:        95,

  // ── Fila 8 ───────────────────────────────────────────────────────────────
  helmet_visor:       96,
  monster_creature:   97,
  weapon_crossbow_2:  98,
  tool_pick:          99,
  coin_orb_2:         100,
  gem_jewel_blue:     101,
  magic_circle_2:     102,
  crystal_teal_7:     103,
  gem_cut:            104,
  potion_pink_2:      105,
  item_canteen:       106,
  item_misc:          107,

  // ── Fila 9 ───────────────────────────────────────────────────────────────
  monster_demon_2:    108,
  monster_variant:    109,
  item_tool_2:        110,
  shield_orb:         111,
  icon_skull_2:       112,
  gem_diamond_blue_3: 113,
  item_ring:          114,
  crystal_green:      115,
  flask_green:        116,
  item_canteen_2:     117,
  item_hook:          118,
  gem_blue_final:     119,
};
