// 'impact'    — el sprite aparece directamente sobre el enemigo
// 'projectile' — el sprite viaja desde el jugador hasta el enemigo
export type SkillEffectType = 'impact' | 'projectile';

export type SkillTarget = 'enemy' | 'self';

export interface SkillConfig {
  abilityId: string;
  effectType: SkillEffectType;
  target?: SkillTarget;   // 'enemy' (por defecto) | 'self' — habilidades sobre el propio jugador
  damage: number;
  range: number;        // tiles
  cooldown: number;     // ms
  spriteKey: string;
  frameCount: number;
  frameRate: number;
  scale: number;
  iconPath?: string;    // imagen para el botón del footer
  speed?: number;       // world pixels/second — solo para 'projectile'
}

export const SKILL_REGISTRY: Record<string, SkillConfig> = {
  ranged_attack: {
    abilityId: 'ranged_attack',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 1500,
    spriteKey: 'skill_fire',
    frameCount: 6,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/fire/icons/fire.png',
  },
  small_fire: {
    abilityId: 'small_fire',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1000,
    spriteKey: 'skill_small_fire',
    frameCount: 6,
    frameRate: 12,
    scale: 1.5,
    iconPath: 'assets/sprites/skills/fire/icons/fuego_pequeno.png',
  },
  fire_flower: {
    abilityId: 'fire_flower',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2500,
    spriteKey: 'skill_fire_flower',
    frameCount: 11,
    frameRate: 12,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/fire/icons/flor_de_fuego.png',
  },
  fire_pillar: {
    abilityId: 'fire_pillar',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1800,
    spriteKey: 'skill_fire_pillar',
    frameCount: 8,
    frameRate: 12,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/fire/icons/pilar_de_fuego.png',
  },
  fire_shield: {
    abilityId: 'fire_shield',
    effectType: 'impact',
    target: 'self',
    damage: 0,
    range: 0,
    cooldown: 4000,
    spriteKey: 'skill_fire_shield',
    frameCount: 8,
    frameRate: 10,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/fire/icons/escudo_de_fuego.png',
  },
  lava_paddle: {
    abilityId: 'lava_paddle',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_lava_paddle',
    frameCount: 10,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/fire/icons/paleta_de_lava.png',
  },
  fireball: {
    abilityId: 'fireball',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 2000,
    spriteKey: 'skill_fireball',
    frameCount: 15,
    frameRate: 14,
    scale: 2,
    speed: 350,
    iconPath: 'assets/sprites/skills/fire/icons/bola_de_fuego.png',
  },
  fire_hurricane: {
    abilityId: 'fire_hurricane',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 3000,
    spriteKey: 'skill_fire_hurricane',
    frameCount: 14,
    frameRate: 12,
    scale: 3,
    iconPath: 'assets/sprites/skills/fire/icons/huracan_de_fuego.png',
  },
  lava_drop: {
    abilityId: 'lava_drop',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 2000,
    spriteKey: 'skill_lava_drop',
    frameCount: 16,
    frameRate: 14,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/fire/icons/gota_de_lava.png',
  },
  magma_geyser: {
    abilityId: 'magma_geyser',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2500,
    spriteKey: 'skill_magma_geyser',
    frameCount: 11,
    frameRate: 12,
    scale: 3,
    iconPath: 'assets/sprites/skills/fire/icons/geiser_de_lava.png',
  },
  water_drop: {
    abilityId: 'water_drop',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1000,
    spriteKey: 'skill_water_drop',
    frameCount: 19,
    frameRate: 14,
    scale: 1.5,
  },
  ice_crystal: {
    abilityId: 'ice_crystal',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_ice_crystal',
    frameCount: 10,
    frameRate: 12,
    scale: 2,
  },
  water_geyser: {
    abilityId: 'water_geyser',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_water_geyser',
    frameCount: 7,
    frameRate: 10,
    scale: 2.5,
  },
  snowflake: {
    abilityId: 'snowflake',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 2500,
    spriteKey: 'skill_snowflake',
    frameCount: 13,
    frameRate: 12,
    scale: 2.5,
  },
  water_splash: {
    abilityId: 'water_splash',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 3000,
    spriteKey: 'skill_water_splash',
    frameCount: 9,
    frameRate: 12,
    scale: 2.5,
  },
  ice_spike: {
    abilityId: 'ice_spike',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 1800,
    spriteKey: 'skill_ice_spike',
    frameCount: 12,
    frameRate: 14,
    scale: 2,
    speed: 380,
  },
  waterball: {
    abilityId: 'waterball',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 2000,
    spriteKey: 'skill_waterball',
    frameCount: 16,
    frameRate: 14,
    scale: 2,
    speed: 350,
  },
  kraken: {
    abilityId: 'kraken',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 5000,
    spriteKey: 'skill_kraken',
    frameCount: 19,
    frameRate: 12,
    scale: 3,
  },
  circle_smoke: {
    abilityId: 'circle_smoke',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_circle_smoke',
    frameCount: 10,
    frameRate: 12,
    scale: 2,
  },
  curved_smoke: {
    abilityId: 'curved_smoke',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 2000,
    spriteKey: 'skill_curved_smoke',
    frameCount: 24,
    frameRate: 16,
    scale: 2,
    speed: 350,
  },
  cycled_smoke: {
    abilityId: 'cycled_smoke',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1000,
    spriteKey: 'skill_cycled_smoke',
    frameCount: 6,
    frameRate: 12,
    scale: 1.5,
  },
  cycled_smoke_long: {
    abilityId: 'cycled_smoke_long',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 2000,
    spriteKey: 'skill_cycled_smoke_long',
    frameCount: 6,
    frameRate: 10,
    scale: 2,
  },
  falling_smoke: {
    abilityId: 'falling_smoke',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2500,
    spriteKey: 'skill_falling_smoke',
    frameCount: 16,
    frameRate: 12,
    scale: 2.5,
  },
  horisontal_smoke: {
    abilityId: 'horisontal_smoke',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 1800,
    spriteKey: 'skill_horisontal_smoke',
    frameCount: 12,
    frameRate: 14,
    scale: 2,
    speed: 380,
  },
  rising_smoke: {
    abilityId: 'rising_smoke',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_rising_smoke',
    frameCount: 14,
    frameRate: 12,
    scale: 2,
  },
  smoke_ghost: {
    abilityId: 'smoke_ghost',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 4000,
    spriteKey: 'skill_smoke_ghost',
    frameCount: 18,
    frameRate: 12,
    scale: 3,
  },
  phoenix: {
    abilityId: 'phoenix',
    effectType: 'projectile',
    damage: 0,
    range: 6,
    cooldown: 5000,
    spriteKey: 'skill_phoenix',
    frameCount: 16,
    frameRate: 12,
    scale: 3,
    speed: 300,
    iconPath: 'assets/sprites/skills/fire/icons/fenix.png',
  },
};
