// 'impact'    — el sprite aparece directamente sobre el enemigo
// 'projectile' — el sprite viaja desde el jugador hasta el enemigo
// 'buff'       — se aplica sobre el jugador: animación self + buffo activo
export type SkillEffectType = 'impact' | 'projectile' | 'buff' | 'dash';

export type SkillTarget = 'enemy' | 'self';

export interface BuffDef {
  stat: string;
  value: number;
}

export interface SkillConfig {
  abilityId: string;
  effectType: SkillEffectType;
  target?: SkillTarget;   // 'enemy' (por defecto) | 'self' — habilidades sobre el propio jugador
  damage: number;
  range: number;        // tiles
  cooldown: number;     // ms
  spriteKey: string;
  frameCount: number;
  frameRate: number;
  scale: number;
  iconPath?: string;    // imagen para el botón del footer
  speed?: number;       // world pixels/second — solo para 'projectile'
  aoeRadius?: number;   // tiles — si se define, daña a todos los enemigos en este radio alrededor del impacto
  buff?: BuffDef;       // si se define, aplica este buffo al jugador al activar la habilidad
  manaCost?: number;   // mana consumido al activar (0 = gratis)
  playerAnim?: boolean; // si true, al lanzar la skill el personaje reproduce su animación de ataque (melee)
  projectileOnce?: boolean; // proyectil: animación una sola vez; el viaje no dura más que la animación
}

export const SKILL_REGISTRY: Record<string, SkillConfig> = {
  dash: {
    abilityId: 'dash',
    effectType: 'dash',
    damage: 0,
    range: 0,
    cooldown: 5000,
    spriteKey: 'skill_cycled_smoke',
    frameCount: 6,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/icon/icons/46.png',
    manaCost: 8,
  },
  ranged_attack: {
    abilityId: 'ranged_attack',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 1500,
    spriteKey: 'skill_fire',
    frameCount: 6,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/fire/icons/fire.png',
    manaCost: 5,
  },
  small_fire: {
    abilityId: 'small_fire',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1000,
    spriteKey: 'skill_small_fire',
    frameCount: 6,
    frameRate: 12,
    scale: 1.5,
    iconPath: 'assets/sprites/skills/fire/icons/fuego_pequeno.png',
    manaCost: 4,
  },
  fire_flower: {
    abilityId: 'fire_flower',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2500,
    spriteKey: 'skill_fire_flower',
    frameCount: 11,
    frameRate: 12,
    scale: 2.5,
    aoeRadius: 1,
    iconPath: 'assets/sprites/skills/fire/icons/flor_de_fuego.png',
    manaCost: 10,
  },
  fire_pillar: {
    abilityId: 'fire_pillar',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1800,
    spriteKey: 'skill_fire_pillar',
    frameCount: 8,
    frameRate: 12,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/fire/icons/pilar_de_fuego.png',
    manaCost: 6,
  },
  fire_shield: {
    abilityId: 'fire_shield',
    effectType: 'buff',
    damage: 0,
    range: 0,
    cooldown: 20000,
    spriteKey: 'skill_fire_shield',
    frameCount: 8,
    frameRate: 10,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/fire/icons/escudo_de_fuego.png',
    buff: { stat: 'defense', value: 10 },
    manaCost: 10,
  },
  lava_paddle: {
    abilityId: 'lava_paddle',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_lava_paddle',
    frameCount: 10,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/fire/icons/paleta_de_lava.png',
    manaCost: 5,
  },
  fireball: {
    abilityId: 'fireball',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 2000,
    spriteKey: 'skill_fireball',
    frameCount: 15,
    frameRate: 14,
    scale: 2,
    speed: 350,
    iconPath: 'assets/sprites/skills/fire/icons/bola_de_fuego.png',
    manaCost: 8,
  },
  fire_hurricane: {
    abilityId: 'fire_hurricane',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 3000,
    spriteKey: 'skill_fire_hurricane',
    frameCount: 14,
    frameRate: 12,
    scale: 3,
    aoeRadius: 2,
    iconPath: 'assets/sprites/skills/fire/icons/huracan_de_fuego.png',
    manaCost: 18,
  },
  lava_drop: {
    abilityId: 'lava_drop',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 2000,
    spriteKey: 'skill_lava_drop',
    frameCount: 16,
    frameRate: 14,
    scale: 2.5,
    aoeRadius: 1,
    iconPath: 'assets/sprites/skills/fire/icons/gota_de_lava.png',
    manaCost: 10,
  },
  magma_geyser: {
    abilityId: 'magma_geyser',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2500,
    spriteKey: 'skill_magma_geyser',
    frameCount: 11,
    frameRate: 12,
    scale: 3,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/fire/icons/geiser_de_lava.png',
    manaCost: 14,
  },
  water_drop: {
    abilityId: 'water_drop',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1000,
    spriteKey: 'skill_water_drop',
    frameCount: 19,
    frameRate: 14,
    scale: 1.5,
    iconPath: 'assets/sprites/skills/water/Water_drop/10.png',
    manaCost: 4,
  },
  ice_crystal: {
    abilityId: 'ice_crystal',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_ice_crystal',
    frameCount: 10,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/water/Ice_crystal/5.png',
    manaCost: 5,
  },
  water_geyser: {
    abilityId: 'water_geyser',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_water_geyser',
    frameCount: 7,
    frameRate: 10,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/water/Geyser/4.png',
    manaCost: 7,
  },
  snowflake: {
    abilityId: 'snowflake',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 2500,
    spriteKey: 'skill_snowflake',
    frameCount: 13,
    frameRate: 12,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/water/Snowflake/7.png',
    manaCost: 8,
  },
  water_splash: {
    abilityId: 'water_splash',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 3000,
    spriteKey: 'skill_water_splash',
    frameCount: 9,
    frameRate: 12,
    scale: 2.5,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/water/Water_and_splash/Splash/5.png',
    manaCost: 14,
  },
  ice_spike: {
    abilityId: 'ice_spike',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 1800,
    spriteKey: 'skill_ice_spike',
    frameCount: 12,
    frameRate: 14,
    scale: 2,
    speed: 380,
    iconPath: 'assets/sprites/skills/water/Ice_spike/6.png',
    manaCost: 7,
  },
  waterball: {
    abilityId: 'waterball',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 2000,
    spriteKey: 'skill_waterball',
    frameCount: 16,
    frameRate: 14,
    scale: 2,
    speed: 350,
    iconPath: 'assets/sprites/skills/water/Waterball/8.png',
    manaCost: 8,
  },
  kraken: {
    abilityId: 'kraken',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 5000,
    spriteKey: 'skill_kraken',
    frameCount: 19,
    frameRate: 12,
    scale: 3,
    aoeRadius: 2,
    iconPath: 'assets/sprites/skills/water/Kraken/10.png',
    manaCost: 25,
  },
  circle_explosion: {
    abilityId: 'circle_explosion',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_circle_explosion',
    frameCount: 10,
    frameRate: 12,
    scale: 2.5,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/explosion/Icons/Icon1.png',
    manaCost: 10,
  },
  explosion: {
    abilityId: 'explosion',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 2000,
    spriteKey: 'skill_explosion',
    frameCount: 10,
    frameRate: 12,
    scale: 3,
    aoeRadius: 2,
    iconPath: 'assets/sprites/skills/explosion/Icons/Icon2.png',
    manaCost: 14,
  },
  explosion_blue_circle: {
    abilityId: 'explosion_blue_circle',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_explosion_blue_circle',
    frameCount: 10,
    frameRate: 12,
    scale: 2.5,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/explosion/Icons/Icon3.png',
    manaCost: 12,
  },
  explosion_blue_oval: {
    abilityId: 'explosion_blue_oval',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 2500,
    spriteKey: 'skill_explosion_blue_oval',
    frameCount: 10,
    frameRate: 12,
    scale: 2.5,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/explosion/Icons/Icon4.png',
    manaCost: 13,
  },
  explosion_gas: {
    abilityId: 'explosion_gas',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_explosion_gas',
    frameCount: 10,
    frameRate: 12,
    scale: 2.5,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/explosion/Icons/Icon5.png',
    manaCost: 12,
  },
  explosion_gas_circle: {
    abilityId: 'explosion_gas_circle',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 3000,
    spriteKey: 'skill_explosion_gas_circle',
    frameCount: 10,
    frameRate: 12,
    scale: 3,
    aoeRadius: 2,
    iconPath: 'assets/sprites/skills/explosion/Icons/Icon6.png',
    manaCost: 16,
  },
  explosion_two_colors: {
    abilityId: 'explosion_two_colors',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 3500,
    spriteKey: 'skill_explosion_two_colors',
    frameCount: 10,
    frameRate: 12,
    scale: 3,
    aoeRadius: 2,
    iconPath: 'assets/sprites/skills/explosion/Icons/Icon7.png',
    manaCost: 18,
  },
  circle_smoke: {
    abilityId: 'circle_smoke',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_circle_smoke',
    frameCount: 10,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/smoker/Circle_smoke/Circle_smoke5.png',
    manaCost: 5,
  },
  curved_smoke: {
    abilityId: 'curved_smoke',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 2000,
    spriteKey: 'skill_curved_smoke',
    frameCount: 24,
    frameRate: 16,
    scale: 2,
    speed: 350,
    iconPath: 'assets/sprites/skills/smoker/Curved_smoke/Curved_smoke12.png',
    manaCost: 8,
  },
  cycled_smoke: {
    abilityId: 'cycled_smoke',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1000,
    spriteKey: 'skill_cycled_smoke',
    frameCount: 6,
    frameRate: 12,
    scale: 1.5,
    iconPath: 'assets/sprites/skills/smoker/Cycled_smoke/Cycled_smoke3.png',
    manaCost: 4,
  },
  cycled_smoke_long: {
    abilityId: 'cycled_smoke_long',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 2000,
    spriteKey: 'skill_cycled_smoke_long',
    frameCount: 6,
    frameRate: 10,
    scale: 2,
    iconPath: 'assets/sprites/skills/smoker/Cycled_smoke_long/Cycled_smoke_long3.png',
    manaCost: 7,
  },
  falling_smoke: {
    abilityId: 'falling_smoke',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2500,
    spriteKey: 'skill_falling_smoke',
    frameCount: 16,
    frameRate: 12,
    scale: 2.5,
    iconPath: 'assets/sprites/skills/smoker/Falling_smoke/Falling_smoke8.png',
    manaCost: 8,
  },
  horisontal_smoke: {
    abilityId: 'horisontal_smoke',
    effectType: 'projectile',
    damage: 0,
    range: 5,
    cooldown: 1800,
    spriteKey: 'skill_horisontal_smoke',
    frameCount: 12,
    frameRate: 14,
    scale: 2,
    speed: 380,
    iconPath: 'assets/sprites/skills/smoker/Horisontal_smoke/Horisontal_smoke6.png',
    manaCost: 7,
  },
  rising_smoke: {
    abilityId: 'rising_smoke',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_rising_smoke',
    frameCount: 14,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/smoker/Rising_smoke/Rising_smoke7.png',
    manaCost: 7,
  },
  smoke_ghost: {
    abilityId: 'smoke_ghost',
    effectType: 'impact',
    damage: 0,
    range: 4,
    cooldown: 4000,
    spriteKey: 'skill_smoke_ghost',
    frameCount: 18,
    frameRate: 12,
    scale: 3,
    iconPath: 'assets/sprites/skills/smoker/Smoke_ghost/Smoke_ghost9.png',
    manaCost: 20,
  },
  smoke_1: {
    abilityId: 'smoke_1',
    effectType: 'impact',
    damage: 0,
    range: 1,            // melee: range*3 = 3 tiles, solo pega de cerca
    cooldown: 1500,
    spriteKey: 'skill_smoke_1',
    frameCount: 7,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/warrior/icon_smoke_01.png',
    playerAnim: true,
    manaCost: 4,
  },
  smoke_2: {
    abilityId: 'smoke_2',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_smoke_2',
    frameCount: 5,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/warrior/icon_smoke_02.png',
    manaCost: 5,
  },
  smoke_3: {
    abilityId: 'smoke_3',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_smoke_3',
    frameCount: 9,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/warrior/icon_smoke_03.png',
    manaCost: 5,
  },
  smoke_4: {
    abilityId: 'smoke_4',
    effectType: 'impact',
    damage: 0,
    range: 3,
    cooldown: 1500,
    spriteKey: 'skill_smoke_4',
    frameCount: 6,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/warrior/icon_smoke_04.png',
    manaCost: 5,
  },
  fire_1: {
    abilityId: 'fire_1',
    effectType: 'impact',          // explosión sobre el enemigo
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_warrior_fire_1',
    frameCount: 7,
    frameRate: 12,
    scale: 2.5,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/warrior/icon_fire_01.png',
    manaCost: 12,
  },
  fire_2: {
    abilityId: 'fire_2',
    effectType: 'projectile',      // bola de fuego que sale del personaje y vuela al enemigo
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_warrior_fire_2',
    frameCount: 12,
    frameRate: 14,
    scale: 2,
    speed: 350,
    projectileOnce: true,          // no repite la animación mientras viaja
    iconPath: 'assets/sprites/skills/warrior/icon_fire_02.png',
    manaCost: 8,
  },
  fire_3: {
    abilityId: 'fire_3',
    effectType: 'impact',          // anillo de fuego sobre el enemigo
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_warrior_fire_3',
    frameCount: 12,
    frameRate: 12,
    scale: 2.5,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/warrior/icon_fire_03.png',
    manaCost: 12,
  },
  blood_1: {
    abilityId: 'blood_1',
    effectType: 'impact',          // estallido de sangre sobre el enemigo
    damage: 0,
    range: 3,
    cooldown: 2000,
    spriteKey: 'skill_blood_1',
    frameCount: 12,
    frameRate: 14,
    scale: 2.5,
    aoeRadius: 1.5,
    iconPath: 'assets/sprites/skills/warrior/icon_blood_01.png',
    manaCost: 12,
  },
  blood_2: {
    abilityId: 'blood_2',
    effectType: 'impact',          // salpicadura sobre el enemigo
    damage: 0,
    range: 3,
    cooldown: 1200,
    spriteKey: 'skill_blood_2',
    frameCount: 4,
    frameRate: 12,
    scale: 2,
    iconPath: 'assets/sprites/skills/warrior/icon_blood_02.png',
    manaCost: 4,
  },
  phoenix: {
    abilityId: 'phoenix',
    effectType: 'projectile',
    damage: 0,
    range: 6,
    cooldown: 5000,
    spriteKey: 'skill_phoenix',
    frameCount: 16,
    frameRate: 12,
    scale: 3,
    speed: 300,
    iconPath: 'assets/sprites/skills/fire/icons/fenix.png',
    manaCost: 25,
  },
  warrior_slash: {
    abilityId: 'warrior_slash',
    effectType: 'impact',
    damage: 0,
    range: 1,            // melee: range*3 = 3 tiles, mismo alcance que el golpe básico
    cooldown: 1500,
    spriteKey: 'skill_warrior_slash',
    frameCount: 10,
    frameRate: 18,
    scale: 1.25,
    iconPath: 'assets/sprites/skills/warrior/icon_attack_01.png',
    playerAnim: true,
    manaCost: 3,
  },
  warrior_slash_2: {
    abilityId: 'warrior_slash_2',
    effectType: 'impact',
    damage: 0,
    range: 1,
    cooldown: 1500,
    spriteKey: 'skill_warrior_slash_2',
    frameCount: 10,
    frameRate: 18,
    scale: 1.25,
    iconPath: 'assets/sprites/skills/warrior/icon_attack_02.png',
    playerAnim: true,
    manaCost: 3,
  },
  warrior_slash_3: {
    abilityId: 'warrior_slash_3',
    effectType: 'impact',
    damage: 0,
    range: 1,
    cooldown: 1500,
    spriteKey: 'skill_warrior_slash_3',
    frameCount: 10,
    frameRate: 18,
    scale: 1.25,
    iconPath: 'assets/sprites/skills/warrior/icon_attack_03.png',
    playerAnim: true,
    manaCost: 3,
  },
  warrior_slash_4: {
    abilityId: 'warrior_slash_4',
    effectType: 'impact',
    damage: 0,
    range: 1,
    cooldown: 1500,
    spriteKey: 'skill_warrior_slash_4',
    frameCount: 8,
    frameRate: 16,
    scale: 1.25,
    iconPath: 'assets/sprites/skills/warrior/icon_attack_04.png',
    playerAnim: true,
    manaCost: 3,
  },
  warrior_slash_5: {
    abilityId: 'warrior_slash_5',
    effectType: 'impact',
    damage: 0,
    range: 1,
    cooldown: 1500,
    spriteKey: 'skill_warrior_slash_5',
    frameCount: 8,
    frameRate: 16,
    scale: 1.25,
    iconPath: 'assets/sprites/skills/warrior/icon_attack_05.png',
    playerAnim: true,
    manaCost: 3,
  },
};
